domain: '.web.rmlab.infn.it'
marketplace:
    apps:
      - name: 'moodle'
        services:
          - nameservice: 'moodle'
            ports:
              - port: 'moodle'
                tcp: 80
                route: 'yes'
            imagename: 'virtuallabs/moodlevlabs'
            env:
              - name: 'DB_HOST'
                type: 'service'
                service: 'mysql'
                value: 'nameservice'
              - name: 'DB_NAME'
                type: 'variable'
                service: 'mysql'
                variable: MYSQL_DATABASE
              - name: 'DB_USER'
                type: 'variable'
                service: 'mysql'
                variable: MYSQL_USER
              - name: 'DB_PASSWD'
                type: 'variable'
                service: 'mysql'
                variable: MYSQL_PASSWORD
              - name: 'WWW_ROOT'
                type: 'route'
                service: 'moodle'
                port: 'moodle'

          - nameservice: 'mysql'
            ports:
              - port: 'mysql'
                tcp: 3306
                route: 'no'
            imagename: 'mysql'
            env:
              - name: 'MYSQL_DATABASE'
                type: 'input'
                description: 'db name'
              - name: 'MYSQL_ROOT_PASSWORD'
                type: 'input'
                description: 'db root pwd'
              - name: 'MYSQL_USER'
                type: 'input'
                description: 'username db'
              - name: 'MYSQL_PASSWORD'
                type: 'input'
                description: 'db pwd'

      - name: 'python'
        services:
          - nameservice: 'psiaboxname'
            ports:
              - port: 'psiabox'
                tcp: 4200
                route: 'yes'
            imagename: 'virtuallabs/psiabox'
            env:
              - name: 'SX_U'
                type: 'input'
                description: 'username'
              - name: 'SX_P'
                type: 'input'
                description: 'password'

      - name: 'vnccentos'
        services:
          - nameservice: 'centos7'
            ports:
              - port: 'novnc'
                tcp: 6901
                route: 'yes'
            imagename: 'virtuallabs/vnccentos'
            env:
              - name: 'VNC_RESOLUTION'
                type: 'static'
                value: '1024x768'
              - name: 'VNC_PWD'
                type: 'input'
                description: 'password'

