marketplace:
    apps:
      - name: 'moodle'
        services:
          - nameservice: 'moodlename'
            ports:
              - port: 'moodle'
                tcp: 80
                route: 'yes'
            imagename: 'virtuallabs/moodlevlabs'
            env:
                DB_HOST: 'moodlemysqlmoodlename'
                DB_NAME: 'moodle'
                DB_USER: 'moodle'
                DB_PASSWD: 'moodle'
                WWW_ROOT: 'http://moodle.web.rmlab.infn.it'

          - nameservice: 'mysqlmoodlename'
            ports:
              - port: 'mysql'
                tcp: 3306
                route: 'no'
            imagename: 'mysql'
            env:
                MYSQL_DATABASE: 'moodle'
                MYSQL_ROOT_PASSWORD: 'moodle'
                MYSQL_USER: 'moodle'
                MYSQL_PASSWORD: 'moodle'

      - name: 'python'
        services:
          - nameservice: 'psiaboxname'
            ports:
              - port: 'psiabox'
                tcp: 4200
                route: 'yes'
            imagename: 'virtuallabs/psiabox'
            env:
                SX_U: 'SX_U'
                SX_P: 'SX_P'

      - name: 'vnccentos'
        services:
          - nameservice: 'vnccentosname'
            ports:
              - port: 'novnc'
                tcp: 6901
                route: 'yes'
            imagename: 'virtuallabs/vnccentos'
            env:
                VNC_RESOLUTION: 'VNC_RESOLUTION'
                VNC_PWD: 'VNC_password'
